//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 4 storyboards.
  struct storyboard {
    /// Storyboard `CreateQRViewController`.
    static let createQRViewController = _R.storyboard.createQRViewController()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `ReaderViewController`.
    static let readerViewController = _R.storyboard.readerViewController()
    /// Storyboard `unkoStoryboard`.
    static let unkoStoryboard = _R.storyboard.unkoStoryboard()
    
    /// `UIStoryboard(name: "CreateQRViewController", bundle: ...)`
    static func createQRViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.createQRViewController)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "ReaderViewController", bundle: ...)`
    static func readerViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.readerViewController)
    }
    
    /// `UIStoryboard(name: "unkoStoryboard", bundle: ...)`
    static func unkoStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.unkoStoryboard)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try unkoStoryboard.validate()
    }
    
    struct createQRViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = CreateQRViewController
      
      let bundle = R.hostingBundle
      let name = "CreateQRViewController"
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct readerViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ReaderViewController
      
      let bundle = R.hostingBundle
      let name = "ReaderViewController"
      
      fileprivate init() {}
    }
    
    struct unkoStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = unkoViewController
      
      let bundle = R.hostingBundle
      let name = "unkoStoryboard"
      let unkoViewController = StoryboardViewControllerResource<unkoViewController>(identifier: "unkoViewController")
      
      func unkoViewController(_: Void = ()) -> unkoViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: unkoViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.unkoStoryboard().unkoViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'unkoViewController' could not be loaded from storyboard 'unkoStoryboard' as 'unkoViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
